import type { PortableTextBlock } from "@portabletext/types";

/** Slug field generated by Sanity `slug` type */
export type SanitySlug = { current?: string };

export type SanityImage = {
  _type?: "image";
  asset?: { _ref?: string; _type?: "reference" };
  alt?: string;
};

export type HomepageSection = {
  _key?: string;
  title?: string;
  content?: string;
};

export type HomepageDocument = {
  _id: string;
  heroTitle?: string | null;
  heroTitleAccent?: string | null;
  heroSubtitle?: string | null;
  heroImage?: SanityImage | null;
  sections?: HomepageSection[] | null;
};

export type ClubDocument = {
  _id: string;
  name?: string | null;
  slug?: SanitySlug | null;
  country?: string | null;
  description?: string | null;
  image?: SanityImage | null;
  isSensitive?: boolean | null;
  order?: number | null;
};

export type StoryDocument = {
  _id: string;
  title?: string | null;
  slug?: SanitySlug | null;
  excerpt?: string | null;
  content?: PortableTextBlock[] | null;
  image?: SanityImage | null;
  country?: string | null;
};

export type FoundationStat = {
  _key?: string;
  label?: string;
  value?: string;
};

export type FoundationDocument = {
  _id: string;
  title?: string | null;
  mission?: string | null;
  vision?: string | null;
  stats?: FoundationStat[] | null;
};
